### ISSUE TITLE
[Suggestion] Add /locate optimization

### ISSUE THREAD

**Issue by IntM4rco** [Wesley1808/ServerCore#100]
Hi, I tried your mod, I noticed that it does a lot of things however I would like to reduce the amount of mods my server has installed. So it would be nice if your mod optimized how structures/biomes are localized so I can finally delete some mods from the server.

**Comment by Wesley1808** [comment]
It already does this to some degree. Used to be more but some of those optimizations got added into vanilla so they were no longer necessary. 

Nobody really gains much from making optimizations that do the exact same thing that other mods already do - just means more code to maintain, probably slower updates and potentially missing changes in the game that causes the optimization to silently break.

Multiple smaller mods are often better than one massive monolith for those reasons. I agree there is probably some overlap already with servercore but afaik only really simple things like item merge radius. I'm just curious why you would want to get rid of                                                    all the other mods.

**Comment by IntM4rco** [comment]
Because more mods=more chances of finding incompatible mods

Anyway, thank you for your reply.
