### ISSUE TITLE
Deleting dynamic settings crashes the server on launch

### ISSUE THREAD

**Issue by Banaando** [Wesley1808/ServerCore#102]
**Describe the bug**
When I delete any of the dynamic settings from the config like it says I should be able to do to disable the option, the server crashes on start.

**Reproduce**

1. Enable the dynamic module in the ServerCore config.
2. Delete any of the dynamic settings from the config.

**Expected behavior**
ServerCore will disable making that behavior dynamic like the config says it will (_Removing a setting from the list will disable it._) and not crash.

**Versions**
ServerCore: 1.5.2
Minecraft: 1.20.6

**Mod incompatibilities**
Happens with no other mods installed.

Logs: https://mclo.gs/FikVp3j

**Comment by Wesley1808** [comment]
Whoops, clearly didn't think that through when designing the new config. I still need the config values (max, min, etc.) for the dynamic values, so deleting them isn't really an option. Properly fixing this will require some minor config changes.

**Comment by Banaando** [comment]
Is there a way to achieve the same effect without deleting config values? Instead maybe like setting the interval to -1 or the increment to 0?

**Comment by Wesley1808** [comment]
I'm not deleting any, just adding a new field to dynamic settings (enabled) and requiring all dynamic settings to be present in the list. Instead lf deleting an entry from the list you'd just set that field to false.
