### ISSUE TITLE
fabric 1.21, please! 

### ISSUE THREAD

**Issue by Legendmanj** [Wesley1808/ServerCore#105]
Please mate, I really please you to update the mod onto fabric 1.21, this seems to give one of the best optimisation to the servers but staying still on 1.20.6 doesn't seem to be good for newly updated servers

if you didn't think/working on the update, please mind doing so 🙏 
if you are considering to work/is already working, thank you mate love you (;

Please again

> if the 1.20.6 mod can be used on 1.21, let me know

**Comment by Wesley1808** [comment]
This mod has been updated to 1.21 for half a month?

**Comment by Legendmanj** [comment]
> This mod has been updated to 1.21 for half a month?

on modrinth, the results seem to show that it is still on 1.20.6 tbh

**Comment by Wesley1808** [comment]
Oh, I didn't update the `Featured Versions`. Check the [versions](https://modrinth.com/mod/servercore/versions) tab for all of them.

**Comment by Legendmanj** [comment]
> Oh, I didn't update the `Featured Versions`. Check the [versions](https://modrinth.com/mod/servercore/versions) tab for all of them.

aight, its updated now ggs

and thankyou (;
