### ISSUE TITLE
servercore-forge-1.5.1+1.20.1 and mcpitanlib-2.3.2-fix.1-1.20.1-forge conflicts

### ISSUE THREAD

**Issue by wuweidmw** [Wesley1808/ServerCore#107]
[minecraft-exported-logs-2024-07-12T18-44-48.log](https://github.com/user-attachments/files/16192814/minecraft-exported-logs-2024-07-12T18-44-48.log)

**Comment by Wesley1808** [comment]
MCPitanLib is shadowing the snakeyaml library but not relocating it. This isn't only a conflict with servercore.
https://github.com/Pitan76/MCPitanLib/issues/6

**Comment by wuweidmw** [comment]
oh，thank you
