### ISSUE TITLE
Will lower mc versions be considered in the future?

### ISSUE THREAD

**Issue by Orisland** [Wesley1808/ServerCore#113]
This is a request, not a bug.
The lower versions of forge/fabric are rarely updated now, and only require one migration to be effective for a long time.
For example, versions 1.16.5 and 1.12.2.
I have now gotten used to installing this mod in any high-version mod-packs to significantly improve performance. This mod has become a necessity for me to play MC. LOL.
If necessary, I can pay you to port the lower version.
My English is very poor, the above content is from the google-translation.

**Comment by Orisland** [comment]
Okay, thanks for your quick reply.
If there is really no hope, forget it.
What a pity. TAT

**Comment by maximuslotro** [comment]
Forge supports mixins at least down to 1.16.5
