### ISSUE TITLE
Enabling optimization settings cause server crash

### ISSUE THREAD

**Issue by 1MiniGinger** [Wesley1808/ServerCore#114]
**Describe the bug**
This is probably a me problem but my default method of problem solving is "ask someone who knows what they're doing." I disabled spawn chunks and enabled dynamic performance checks, but I didn't want view distance to be impacted so I deleted those lines as instructed in the config file. On server restart, it crashed with the error "VIEW_DISTANCE has not been initialized yet!"

**Reproduce**
1. Run Fantasy MC Fabric modpack, remove Xaero's minimap and world map and Observable, add Simple Voice Chat, JourneyMap, ServerCore, Very Many Players, and WorldEdit.
2. Disable spawn chunks and enable dynamic performance checks in ServerCore config. Delete view distance from settings to be affected by dynamic performance checks.
3. restart server
4. Crash
5. 
[crash-2024-08-13_20.51.53-server.txt](https://github.com/user-attachments/files/16605655/crash-2024-08-13_20.51.53-server.txt)

**Expected behavior**
to start the server as normal

**Versions** -Latest is not a version!
ServerCore: servercore-fabric-1.5.1+1.20.1
Minecraft: 1.20.1
Fantasy MC Fabric modpack: 1.20.1

**Mod incompatibilities**
I don't think it's a mod compatibility issue but also there are over 360 mods in the pack so who knows.

**Comment by Wesley1808** [comment]
This is fixed in newer versions of the mod, in 1.5.1 you can't delete any of them like that. You can work around disabling it by setting the max and min value to the same value (being the view distance you want to run it at), so it will never try to change it.

**Comment by 1MiniGinger** [comment]
Thanks! I will do that then.
