### ISSUE TITLE
not reading config file

### ISSUE THREAD

**Issue by troyheady2** [Wesley1808/ServerCore#119]
**Describe the bug**
i assume this is user error, but I can't get ServerCore to read the config file.  
Can you please tell me what i am doing wrong?

**Reproduce**
running modpack All the Mods 8 and placed optimized examples from github into the config/servercore   (lowercase?) dir
and mod jar in mods directory

**Expected behavior**
no messages about issues in startup / logs
when i use the /servercore commands i do not see and of the changes
and saving does not update or change things on restart

**Versions** -Latest is not a version!
ServerCore:  V1.3.6
Minecraft: 1.19.2

**Mod incompatibilities**

kermitcraft:4d3a00cb-bcb8-45cd-82a5-2dfe41277a96/config/servercore
▶ ls -al
total 32
drwxr-xr-x  2 crafty crafty  4096 Oct 25 08:17 .
drwxr-xr-x 39 crafty crafty 12288 Nov 10 13:47 ..
-rw-r--r--  1 crafty crafty 10527 Oct 25 08:16 config.yml
-rw-r--r--  1 crafty crafty  1203 Oct 25 08:17 optimizations.yml

kermitcraft:servers/4d3a00cb-bcb8-45cd-82a5-2dfe41277a96/logs                                                                   ⍉
▶ grep -i servercore latest.log
[12Nov2024 01:19:34.207] [modloading-worker-0/INFO] [me.wesley1808.servercore.common.ServerCore/]: [ServerCore] Loaded V1.3.6+1.19.2!

**Comment by Wesley1808** [comment]
You're still on 1.19.2, which is before the configs got reworked.
Instead of `servercore/config.yml` and `servercore/optimizations.yml` you're looking for `servercore.toml`

I don't have preset examples of a more 'optimized' config for it but most options should be similarly named and structured so you can kinda copy them over.
