### ISSUE TITLE
Problem with a Datatpack

### ISSUE THREAD

**Issue by SugarDaddii** [Wesley1808/ServerCore#12]
**Describe the bug**
Hello,
iam using a Datapack (https://www.planetminecraft.com/data-pack/economyplus/) and when iam using this mod some function will be killed or not working correctly!
For Example
https://imgur.com/a/QzDHLil
under price shpuld be a number...and these numbers are invisible villager

**Reproduce**
Iam deleting your mod Dtatpack will function again!

**Expected behavior**
A clear description of what you expected to happen.

ServerCore: servercore-1.2.6-1.18.1
Minecraft: Minecraft 1.18.1 Fabric 0.12.12

**Comment by Wesley1808** [comment]
Unable to reproduce, nametags work fine for me with the mod both serverside (and clientside in case this was a clientside issue).
That includes the price numbers.

**Comment by SugarDaddii** [comment]
iam using your mod on a 1.18.1 fabric 0.12.12 server and there i dont get the numbers correctly eather the normal functions!
i tested all mods and when i delete your mod it was doing well again! i dont change any config only add/remove the mod

**Comment by Wesley1808** [comment]
Try setting `disable_spawn_chunks` in the config (servercore.toml) to `false`.
I think that datapack might require the spawn chunks to be loaded for some reason, which is rather unusual.
Reason it worked for me earlier was because I was loading those chunks myself - after flying further out it no longer worked, but turning that setting to false and restarting seems to work consistently.

**Comment by SugarDaddii** [comment]
no sry thats wasnt the solution...
this is how it looks like:
1. https://imgur.com/a/u2hZabo
2. https://imgur.com/a/QVsEwdr
this how it should looks like
1. https://imgur.com/a/iiovUbX
2. https://imgur.com/a/xMXbr8D

**Comment by SugarDaddii** [comment]
sry i is function again! settings wasnt saved ... thx very much

**Comment by Wesley1808** [comment]
Have you tried running it with just the datapack, servercore with the config setting and completely restarting the server?
I am unable to reproduce this, with the above setup everything works perfectly fine on my end.
