### ISSUE TITLE
Getting a mob count related server crash 

### ISSUE THREAD

**Issue by Saereth** [Wesley1808/ServerCore#120]
**Describe the bug**
The server crashes when mobs (maybe only zombies) die. Servercore calls "mobCounts." counts," which returns null and crashes the server.

**Reproduce**

    Kill zombie.
    Zombie causes ticking entity. This doesn't happen every time, only once or twice an hour. For some server owners it never happens, hard to reproduce.

**Expected behavior**
No crash

**Versions** -Latest is not a version!
ServerCore: servercore-neoforge-1.5.5+1.21.1
Minecraft: 1.21.1

**Mod incompatibilities**
This is with the FTB Evolution modpack which has like 400 mods nearly so hard to say what may be conflicting if anything here.

**Comment by Wesley1808** [comment]
Normally speaking that field should never be null - its moonrise that sets the field to null, and there's effectively no other way for me to avoid using that field for the following features:
- enforce-mobcap (look for `enforce-mobcap: true` in the config)
- /mobcaps (command)

So for now best solution would be to configure it so those features are turned off if you use moonrise.

**Comment by Saereth** [comment]
oh gotcha, yeah we actually removed moonrise due to some other compatibility issues in this update so should no longer be a problem for this pack. Ty for the clarification
