### ISSUE TITLE
Bats don't stop moving after changing activation range

### ISSUE THREAD

**Issue by TypicalTropic** [Wesley1808/ServerCore#13]
**Describe the bug**
Bats Don't stop moving from any of the categories under the activation range

**Reproduce**
animal_activation_range =1
flying_activation_range=1
neutral_activation_range=1
misc_activation_range = 1

Neither of these turns them off 

**Expected behaviour**
Bats not to move when out of the 1 chunk distance 

**Versions** -Latest is not a version!
ServerCore:1.2.6
Minecraft:1.18.1

**Comment by Wesley1808** [comment]
Bats are ambient creatures, but not considered flying mobs (judging by the game's code).
This means that whenever they are not on the ground (flying), they will be immunized from activation ranges.

Another thing is that entity activation range is quite a bit more advanced than just "freeze entity over x chunks".  It also includes immunity checks and such to make entities not ticking far less noticeable.

Also note that activation ranges are counted in blocks, not chunks. Setting that value to 1 means they won't activate unless you hug them.

**Comment by TypicalTropic** [comment]
Thank you also keep up the good work mate 👍
