### ISSUE TITLE
ServerCore not allowing combination of Elytra and Chestpiece on Anvil with Vanilla Tweaks Armored Elytra

### ISSUE THREAD

**Issue by JAladwan** [Wesley1808/ServerCore#15]
**Describe the bug**
ServerCore prevents the Vanilla Tweaks Armored Elytra datapack from combining items, still allows separation on grindstones. There are no logs that I can find that explains why this is happening, I found out by uninstalling each mod one by one to see what would solve it and everything but ServerCore passed the test.

**Reproduce**
Steps to reproduce the behavior: Install ServerCore, Install Armored Elytra datapack, attempt to combine elytra and chestpiece on an anvil

**Expected behavior**
Elytra and Chestpiece to combine when thrown on an anvil
**Versions** -Latest is not a version!
ServerCore: 1.2.6
Minecraft: 1.18.1

**Mod incompatibilities**
Just gonna list all my other mods but I don't think any are causing issues.
Lithium
Starlight (Previously Phosphor, but was broken on both mods)
Universal Graves
Carpet
Carpet Extra
BlockBot

**Comment by Wesley1808** [comment]
Some datapacks seem to require the spawn chunks to be loaded to function correctly.
Set `disable_spawn_chunks` in servercore.toml to `false`, that should resolve those issues.

I'm going to turning this off by default for future updates aswell, because of its potential to break datapacks.
