### ISSUE TITLE
new version Crashes at start, old version works without problems.

### ISSUE THREAD

**Issue by TheButterbrotMan** [Wesley1808/ServerCore#17]
**Describe the bug**
A clear description of what the bug is.

**Versions** -Latest is not a version!
ServerCore: ServerCore-1.2.7-1.18.1
Minecraft: 1.18.1

**Mod incompatibilities**
https://www.curseforge.com/minecraft/modpacks/deathdusk

https://pastebin.com/7DDU0MT5

**Comment by Wesley1808** [comment]
Could you try launching the game without ksyxis? ServerCore's setting `disable_spawn_chunks` does essentially the same thing, if you enable it in the config. Thats about all the conflicts I can find where SC plays a role in that log.

**Comment by Wesley1808** [comment]
Alternatively you could try out the most recent build from github actions (from commit 1336860b324bcfa403e97e85c31870ccafcbaef9) 
and see if that fixes the issue for you.

**Comment by TheButterbrotMan** [comment]
> Alternatively you could try out the most recent build from github actions (from commit [1336860](https://github.com/Wesley1808/ServerCore/commit/1336860b324bcfa403e97e85c31870ccafcbaef9)) and see if that fixes the issue for you.

How can i try it out? Im not that technically :(

So ksyxis is redundant?

**Comment by Wesley1808** [comment]
> How can i try it out? Im not that technically :(

You can download it from [here](https://github.com/Wesley1808/ServerCore/actions/runs/1675023824).


> So ksyxis is redundant?

Not necessarily, ksyxis still gives you the option to get rid of the world loading screen without completely stopping the spawn chunks from being loaded. The above link will allow you to use both options together though, if necessary.

**Comment by TheButterbrotMan** [comment]
The fix work. When will it be pushed, so that i can implent it in my modpack.

**Comment by Wesley1808** [comment]
I reuploaded the mod on both curseforge & modrinth.
Hope that helps!

**Comment by TheButterbrotMan** [comment]
Thank you!

**Comment by TheButterbrotMan** [comment]
When will it be avaiable in curseforge Launcher?

**Comment by Wesley1808** [comment]
I don't know. I uploaded it to CurseForge (as a reupload of 1.2.7), so I assume it should be there aswell.
