### ISSUE TITLE
Could you add 32view distance and 32 simulation distance?

### ISSUE THREAD

**Issue by TheButterbrotMan** [Wesley1808/ServerCore#18]
Would be really nice if you could add 32 view & simulation distance.

# Modifies mobcaps, no-chunk-tick, simulation and view-distance depending on the MSPT.
[dynamic]
	# (Default = false) Enables this feature.
	enabled = fallse
	# (Default = 35) The average MSPT to target.
	target_mspt = 25
	# (Default = 15) The amount of seconds between dynamic performance updates.
	update_rate = 15
	# (Default = 150) The amount of seconds between dynamic viewdistance updates.
	# This value is separate from the other checks because it makes all clients reload their chunks.
	view_distance_update_rate = 150
	# (Default = [Max: 10, Min: 2]) Distance in which random ticks and mobspawning can happen.
	max_chunk_tick_distance = 10
	min_chunk_tick_distance = 2
	# (Default = [Max: 10, Min: 2]) Distance in which the world will tick, similar to no-tick-vd.
	max_simulation_distance = 32
	min_simulation_distance = 5
	# (Default = [Max: 10, Min: 2]) Distance in which the world will render.
	max_view_distance = 32
	min_view_distance = 2
	# (Default = [Max: 1.0, Min: 0.3]) Global multiplier that decides the percentage of the mobcap to be used.
	max_mobcap = 1.0
	min_mobcap = 0.3

**Comment by Wesley1808** [comment]
Can't you already do this? Does something happen if you try to launch the game with that config?

By the way, make sure that de `viewDistance` property in `server.properties` is 32 chunks, because it will "start* at whatever value is assigned to that property.

**Comment by TheButterbrotMan** [comment]
Ill try it.

**Comment by TheButterbrotMan** [comment]
I was not aware of this.
>By the way, make sure that the viewDistance property in server.properties is 32 chunks, because it will start at whatever value is assigned to that property.
