### ISSUE TITLE
Not dynamically adjusting view distance

### ISSUE THREAD

**Issue by aspnn** [Wesley1808/ServerCore#19]
**Describe the bug**
The view distance does not change despite MSPT being under/above the target

**Reproduce**
Install servercore. Config is set to target mspt 50, max view distance 16, minimum 4 (same for sim distance and chunk tick distance)
The server will only use the distances specified in server.properties

**Expected behavior**
Server should adjust based on MSPT, when set to 4 in server.properties it will not adjust upwards when server load is low, when at 16 in server.properties it does not adjust when server load is high.

**Versions** -Latest is not a version!
ServerCore: 1.2.7-1.18.1
Minecraft: 1.18.1 fabric 0.12.12

**Mod incompatibilities**
All installed mods on the server:
alternate currrent 1.1.0
armorstand edtior 1.3.1
bfapi
cloth-config 6.1.48
fabric api 0.45.0
fabric language kotlin 1.7.1
fabricsit 1.7.1
fabrilous updater 2.5
fastfurnace 6.0.1.
ferritecore 4.0.0.
invisframes 2.1.1.
krypton 0.1.6.
ksyxis 1.1.
lazydfu 0.1.2.
lithium 0.7.6.
minimotd 2.0.5
modmenu 3.0.1.

**Comment by Wesley1808** [comment]
Could you send the config file over aswell? This feature is disabled by default. You can also check all these values using 
`/servercore status` to check if its not still modifying a different value (it doesn't change all of them at the same time).

**Comment by aspnn** [comment]
`# Modifies mobcaps, no-chunk-tick, simulation and view-distance depending on the MSPT.
[dynamic]
	# (Default = false) Enables this feature.
	enabled = true
	# (Default = 35) The average MSPT to target.
	target_mspt = 40
	# (Default = [Max: 10, Min: 2]) Distance in which random ticks and mobspawning can happen.
	max_chunk_tick_distance = 10
	min_chunk_tick_distance = 2
	# (Default = [Max: 10, Min: 2]) Distance in which the world will tick, similar to no-tick-vd.
	max_simulation_distance = 10
	min_simulation_distance = 2
	# (Default = [Max: 10, Min: 2]) Distance in which the world will render.
	max_view_distance = 16
	min_view_distance = 2
	# (Default = [Max: 1.0, Min: 0.3]) Global multiplier that decides the percentage of the mobcap to be used.
	max_mobcap = 1.0
	min_mobcap = 0.3
`
You may be right about the 150 second update timer. I'll wait and try again.
servercore status also says that chunk tick distance was at 10 while all others were at 4
