### ISSUE TITLE
Incompatibility with YUNG's API

### ISSUE THREAD

**Issue by ioanvl** [Wesley1808/ServerCore#24]
HI, 

There is an incompatibility with [YUNG's API](https://www.curseforge.com/minecraft/mc-mods/yungs-api-fabric)

The game crashes with the minimum mods installed (fabric_api + cloth + yungs_api + servercore) with error:
`java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'fabric-api-lookup-api-v1'!
Exit Code: -1`

ServerCore 1.2.8 - YUNG's API 2.0.7 - Fabric Loader0.13.3/1.18.2

Both seem to try and modify similar paths
[latest.log](https://github.com/Wesley1808/ServerCore/files/8446621/latest.log)

I have created a [mirror issue](https://github.com/yungnickyoung/YUNGs-API/issues/29) on their git.

**Comment by Wesley1808** [comment]
This exact issue has already been reported (and resolved) in both repositories. #23 

From yung's side, their mixin will no longer activate unless its used within dev environment.

From my side, it won't activate anymore if the `disable_spawn_chunks` option is set to false (although that only matters if both are used in dev env).

[Link to the most recent 1.18.2 build (not yet released)](https://github.com/Wesley1808/ServerCore/actions/runs/2098078938)

**Comment by ioanvl** [comment]
Ah, that's great to hear, thanks a lot for the quick response!
