### ISSUE TITLE
Config is reset on restart

### ISSUE THREAD

**Issue by Labotomy** [Wesley1808/ServerCore#25]
When you restart the server after editing the config file, the config is reset to default values.

**Reproduce**
Add to mods folder, generate config file by starting the server, (stopping the server is optional) edit the config file, save the file, restart the server.

**Expected behavior**
Expect the changed config file to use and retain it's edited values.

**Versions** -Latest is not a version!
ServerCore: 1.2.8
Minecraft: 1.18.1

**Comment by Wesley1808** [comment]
ServerCore saves the config file when the server shuts down, based on entries that were running on the server itself.
When you change entries in the config file, it doesn't immediately change entries on the actual server. 

There's 2 commands that handle this:

- /servercore config reload -> takes all values from the actual config file, and puts them running on the server.
- /servercore config save -> takes all values from the server, and saves them __to__ the config file.

I assume you were most likely changing the config file without actually synchronizing these values on the server.
Which would indeed make it override those changes as server shutdown essentially does the same as `/sc config save`.

**Comment by Labotomy** [comment]
What a hassle, will try running the commands from the console.
The behavior has happened whether the config is edited while the server is stopped or not. 

There is no one in game to run the commands.

**Comment by Wesley1808** [comment]
It can only edit specific config entries on startup if they turn out to be invalid.
It prints an error in the log aswell though, but the alternative would be a server crash.

And if I did it the other way around people would complain that the ingame configs don't save ¯\_(ツ)_/¯

**Comment by Labotomy** [comment]
I did edit the config while the server was not running, it still overwrote them with defaults.

**Comment by Wesley1808** [comment]
Well, if you ever do run into this problem again, could you send the config file over before it is 'overwritten'?
I haven't been able to reproduce that on my end, so its most likely something with the config file itself that isn't correctly formatted.

**Comment by Labotomy** [comment]
[servercore.txt](https://github.com/Wesley1808/ServerCore/files/8467142/servercore.txt)

Had to change the extension since github wouldn't allow it to attach.  I suspect it has to do more with fabric than the config.

**Comment by Labotomy** [comment]
Manually running the command mitigates the issue.
