### ISSUE TITLE
Dynamic view-distance Farsight support

### ISSUE THREAD

**Issue by El13B** [Wesley1808/ServerCore#26]
**Describe the feature**
Farsight is a mod that enables the client to not refresh chunks every time the render distance changes. The [dynamic view](https://github.com/ldtteam/DynView/tree/fabric1.18.2) mod changes render distance without triggering the accursed chunk reset thanks to the farsight mod, could this mod also support farsight? 

If not a boolean setting to toggle off only the dynamic render distance would be awesome, it seems setting the view_distance_update_rate to 0 resets it back to it's original value.

**Comment by Wesley1808** [comment]
Another way to do that would be by setting the `min_view_distance` at the same value as `max_view_distance` or higher.

**Comment by El13B** [comment]
currently trying it out on a singleplayer environment

**Comment by Wesley1808** [comment]
That would make sense. If used on the client servercore will also update the viewdistance and simulation distance sliders accordingly. I imagine changing that might trigger a chunk reload, similar to changing the slider ingame?

About disabling it, refer to the first line on the message above.

**Comment by El13B** [comment]
I've just tried this and can confirm it still triggers a chunk reload

**Comment by Wesley1808** [comment]
> Another way to do that would be by setting the min_view_distance at the same value as max_view_distance or higher.

Nevermind that actually, if the viewdistance isn't at that specific value it will still try to increase it until that point (and then stop, unless changed again).

Maybe? a workaround would be to set the `max_view_distance` to 2, and `min_view_distance` to some really high value it'll never reach, as it *most likely shouldn't* be able to modify anything within that range. 
Thats not very intuitive for the user though... but I also don't want to increase the config too much if not necessary.

I'm probably gonna look at taking out the option slider modifications first, to check if viewdistances still properly change on singleplayer despite the option not being modified.

**Comment by Wesley1808** [comment]
> I'm probably gonna look at taking out the option slider modifications first, to check if viewdistances still properly change on singleplayer despite the option not being modified.

Sadly, it doesn't. If the distance slider isn't modified, then the viewdistance won't change in singleplayer either.

**Comment by Wesley1808** [comment]
With commit https://github.com/Wesley1808/ServerCore/commit/f729f3aea576104ba9744bf7048a449f9dfd034d or later you will be able to easily disable specific dynamic settings (such as viewdistance in this case), by removing it from the `setting_order` config entry.
