### ISSUE TITLE
Lobotomize Villagers disables itself

### ISSUE THREAD

**Issue by Chuffs** [Wesley1808/ServerCore#27]
**Describe the bug**
lobotomize_villagers value not staying set in config

**Reproduce**
Change the value and start server, check the value of lobotomize_villagers with server running

**Expected behavior**
Value should stay as set in config

**Versions**
ServerCore: 1.2.8
Minecraft: 1.18.2

**Mod incompatibilities**
List any installed mods you think might play a role in causing this bug.

**Comment by Wesley1808** [comment]
I cannot reproduce this behavior - it is staying set to whatever value I set it to by walking through these steps.
Please do make sure the value you enter is valid: true or false, and that you actually save the file before starting up the server.

If that doesn't help, could you send the log file when it happens?

**Comment by Chuffs** [comment]
All good, I seem to have fixed the issue. I re-installed all my mods and left out ones that I didn't think were necessary and it is now working as intended - must have had an incompatible mod installed.

Mods that are different between reinstalls -
alternate-current-mc1.18-1.1.0.jar
Clumps-fabric-1.18.2-8.0.0+7.jar - duplicate feature perhaps?
servertick-mc1.18-1.6.jar
smoothboot-fabric-1.18.2-1.7.0.jar
starlight-1.0.2+fabric.89b8d9f.jar
vmp-fabric-mc1.18.2-0.2.0+beta.3.17-all.jar
