### ISSUE TITLE
/servercore status is not getting parsed correctly

### ISSUE THREAD

**Issue by noxifoxi** [Wesley1808/ServerCore#30]
**Describe the bug**
see title, example:
![image](https://user-images.githubusercontent.com/293639/172651599-e0f45d0a-d4bb-400c-97a5-723ce32920a6.png)

**Reproduce**
type `/servercore status`

**Expected behavior**
correct parsing and displaying the values

**Versions** -Latest is not a version!
ServerCore: servercore-1.3.0-1.19
Minecraft: 1.19

**Mod incompatibilities**

- carpet-extra-1.19-1.4.79.jar
- fabric-api-0.55.2+1.19.jar
- fabric-carpet-1.19-1.4.79+v220607.jar
- lithium-fabric-mc1.19-0.8.0-SNAPSHOT.jar
- starlight-1.1.0+fabric.eb9df34.jar

**Comment by Wesley1808** [comment]
I might've forgotten to mention in the changelog that the 1.19 version changes how variables work in the messages.
For example: `%VIEW_DISTANCE%` -> `${view_distance}`

The easiest way to resolve this, is to head to the config `servercore.toml` and just completely delete the `[commands]` section.
Then use `/sc config reload` and it will automatically regenerate the messages with the 'new' values.

**Comment by noxifoxi** [comment]
thanks, it works now!
