### ISSUE TITLE
Spawners / Reinforcements taking up the mob cap

### ISSUE THREAD

**Issue by skerit** [Wesley1808/ServerCore#38]
It's not really a bug, but more something I'd like to get your input on.

ServerCore's dynamic scaling of the mobcap (and other values) is really great, it keeps my server running smooth.
But because mob spawners & zombie reinforcements bypass the mobcaps in vanilla anyway, they're also exempt of the dynamic scaling.

Because of this, when my mobcap modifier goes down to 0.3, there's a zombie spawner + reinforcement farm one of my player uses that basically starts to act as a mob switch.

Would it make sense to make spawners & reinforcements respect the scaled mobcap modifier somehow?

**Comment by Wesley1808** [comment]
To be fair, thats more of a vanilla 'problem'. If you make said reinforcement - or any other type of mobfarm that counts to - but doesn't care about the mobcap - large enough it would pretty much act as a mob switch aswell - with the fix being to bring in enough players loading different chunks to up the global mobcap high enough so it doesn't affect it anymore.

One of the main appeals of using such a farm is that it isn't controlled by any mobcap, but I do know that it can be an issue on some (especially also larger) servers. Personally I also run some patches alongside it (not in ServerCore) that limit the amount of mobs mobspawners or reinforcements can spawn (depending on nearby mobs).

Mobswitches can still easily happen though, if some player with a shulker farm decides to not kill the shulkers for a bit too long.
