### ISSUE TITLE
The MSPT rises when the player connects server

### ISSUE THREAD

**Issue by MrJorman** [Wesley1808/ServerCore#39]
When a player connects, my MSPT goes up from 4 to 15-20 and runs the server.

ServerCore: latest
Minecraft: 1.19 Fabric

I had such a problem on Forge, but I fixed it with some kind of mod, like FastLoad or krypton or ksyxis, but then I put a lot of optimization and I don't know how to fix it. When a player connects to the server, it freezes.

**Comment by Wesley1808** [comment]
Whenever a player connects to the server, they will often tick before the chunks below them are loaded in. This causes that chunk to sync load, which causes a lagspike until that chunk is fully loaded.

FastLoad and Ksyxis do not help with this at all.  On the server they only just make the initial world loading (at startup) faster, nothing else. Krypton does network optimizations and doesn't really touch that either.

As far as I know, currently there isn't really any clean solution to loading these player-login chunks async, but C2ME might be implementing that feature eventually (at least they said it was planned at some point).

But, my main question here: How is ServerCore involved in these lagspikes that makes you create an issue here? to me it seems more like a help / support thread or maybe a feature request.

**Comment by MrJorman** [comment]
check pls my config

[c2me.txt](https://github.com/Wesley1
[servercore.txt](https://github.com/Wesley1808/ServerCore/files/9092353/servercore.txt)
808/ServerCore/files/9092352/c2me.txt)

**Comment by Wesley1808** [comment]
Closing this as this isn't really an issue with servercore, and because async chunks for player login have now been implemented in C2ME.
