### ISSUE TITLE
Causes Solar Strike entity from Arcanus to never die

### ISSUE THREAD

**Issue by CammiePone** [Wesley1808/ServerCore#51]
So, this has been reported to me in https://github.com/CammiePone/Arcanus/issues/76 and to Dark RPG in https://github.com/gamerpotion/DarkRPG/issues/42, and finally figured out it was ServerCore causing the problem.

The issue is whenever a Solar Strike entity is spawned, it doesnt go away, despite its normal behaviour being despawning after a few ticks. With Arcanus alone, the issue does not occur, but with ServerCore and Arcanus, the issue starts happening.

I have confirmed this is an issue with ServerCore 1.3.2 and Arcanus 1.30 on Minecraft 1.19.2. I dont know what change ServerCore made is causing it, but it results in people being killed when they respawn on multiplayer servers until someone runs /kill on all Solar Strike entities, so it's a pretty critical bug and likely affects other entities from other mods.

**Comment by Wesley1808** [comment]
If I had to guess it would probably be related to entity activation range. How does arcanus despawn its solar strikes normally?
A potential fix for these sorts of modded entities could be to just set `misc_activation_range` to -1 in the config, which should include most of these "misc" entities like spells and projectiles.

**Comment by Wesley1808** [comment]
> I have confirmed this is an issue with ServerCore 1.3.2 and Arcanus 1.30 on Minecraft 1.19.2. I dont know what change ServerCore made is causing it, but it results in people being killed when they respawn on multiplayer servers until someone runs /kill on all Solar Strike entities, so it's a pretty critical bug and likely affects other entities from other mods.

Could you provide steps to reproduce the issue? I can't seem to get it to work with just Arcanus 1.30 and ServerCore, even with activation range enabled - so I'm not exactly sure what would be causing the issue.

**Comment by Wesley1808** [comment]
I pushed a build to both Modrinth and CurseForge under version 1.3.3-1.19.2 where this issue *should* be resolved now.
