### ISSUE TITLE
Not a bug, more of a request

### ISSUE THREAD

**Issue by LurgenAU** [Wesley1808/ServerCore#58]
I would very much love to see ServerCore ported to Forge 1.18.2. I can see you've started on a 1.19.x beta, which is awesome but a large number of 1.18.2 modpacks are popular right now and this could really help me out with some performance tuning. I used this mod previously on Fabric (1.18.2) and it was fantastic.

Please don't make me beg!

**Comment by Wesley1808** [comment]
Any version of the forge loader under 1.19.1 causes me a lot of trouble with servercore's dependencies and a dozen other badly explained random errors. I don't really support 1.18 anymore for fabric either, and don't particularly feel like rewriting most of the build scripts and maybe even part of the codebase to (maybe?) hack a 1.18.2 version together that works on forge.

I can backport version 1.3.5 for both forge and fabric to 1.19.3, 1.19.2 and 1.19.1 though.

**Comment by LurgenAU** [comment]
Sorry to hear that - packs like All The Mods 7 could really use your tool, it'd make a huge difference but I do get it.

**Comment by Wesley1808** [comment]
In the end I did manage to backport it to 1.18.2 - I ran into some difficult to decipher but (surprisingly) simple to actually fix errors in both dev & prod environment.

They will be on curseforge aswell once they get reviewed.

**Comment by LurgenAU** [comment]
Sorry for the delay - I got around to testing it, and can't get it to boot. Conflicts with the mixins I think. This was tested against All The Mods 7 (Forge) running on Magma, logfile is here: https://pastebin.com/ym75gJjr

**Comment by Wesley1808** [comment]
There do seem to be some really weird changes in the local variable table of the target method, which do not exist in vanilla. Consid
