### ISSUE TITLE
[Forge] Particles doesn't go away, persistent particles

### ISSUE THREAD

**Issue by superhealing** [Wesley1808/ServerCore#60]
**Describe the bug**
Particles will stay forever, no matter time and server reboots. As example, i put potion particles (eg lingering) will stay forever there, persists server reboots, and cause lag for client-side users not server-side.

**Reproduce**
I managed to reproduce with Vault Hunters 3rd Edition and simply added the servercore, got the healing ability, throw away into ground, that particle stayed forever, no way to clear. I didn't not able to replicate on vanilla 1.18.2 with the mod himself

**Expected behavior**
To disappear?

**Versions** -Latest is not a version!
ServerCore: ServerCore-Forge-1.3.5+1.18.2
Minecraft: 1.18.2
Modpack : https://www.curseforge.com/minecraft/modpacks/vault-hunters-1-18-2/files/4516811

**Mod incompatibilities**
Vault mod (mod for the pack)
I don't think anything else, if you need more data i will be happy to provide.

**Comment by Wesley1808** [comment]
Area effect clouds (from vanilla lingering potions) seem to disappear just fine for me. I'm also not sure what you mean by the healing ability (not familiar with the modpack).

Can you provide your config file (servercore.toml), and more specific reproduction steps (like about the healing ability thing), so I can see if I can reproduce it with those.

**Comment by Wesley1808** [comment]
I'm pretty sure this was caused by older versions of 1.18.2 Forge not supporting JiJ libraries (in my case MixinExtras) correctly.
If this issue still remains in the latest version of Forge for 1.18.2, please let me know.
