### ISSUE TITLE
FTBEssentials 1.19.2 Forge - crash server when in type /rtp

### ISSUE THREAD

**Issue by MrJorman** [Wesley1808/ServerCore#62]
FTBEssentials 1.19.2 Forge - crash server when in type /rtp

Your mod ServerCore 1.19.2 Forge + FTBEssentials + /rtp command = crash server. i use default config your mod.

**Comment by Wesley1808** [comment]
Can you provide the crash report from when it crashed from /rtp-ing?

**Comment by MrJorman** [comment]
Sorry buddy, I can’t do it anymore, try it yourself, I have people playing on the server.

**Comment by MrJorman** [comment]
Just install Forge server and put ServerCore + FTBEssentials mod there and type /rtp

**Comment by Wesley1808** [comment]
If it crashed before, said crash report would already have been generated. No need to intentionally try to crash it again.

**Comment by MrJorman** [comment]
It crashes every time I write /rtp, ALWAYS!

**Comment by MrJorman** [comment]
@Wesley1808 
[crash-2023-05-29_04.21.12-server.txt](https://github.com/Wesley1808/ServerCore/files/11587383/crash-2023-05-29_04.21.12-server.txt)

**Comment by Wesley1808** [comment]
Just remove the line `"optimizations.tickets.ServerLevelMixin",` in `servercore.common.mixins.json` inside the .jar file you already have. That should resolve the issue aswell.
