### ISSUE TITLE
check pls my timings. 20 online.

### ISSUE THREAD

**Issue by MrJorman** [Wesley1808/ServerCore#63]
i use your mod , bro, help me pls. check my timings: https://spark.lucko.me/d4aEmzVi7H

Forge 1.19.2 IC2, 20 online = MSPT ~ 25

Fabric 40 online ~ mspt 8.9

**Comment by Wesley1808** [comment]
If you want support with checking spark reports / timings, you should ask for it in discord or some place similar. Github issues is really not the place for this.

Also, if you do end up asking this somewhere else, it may be helpful to give some context:
- What should anyone checking your timings be looking for? It appears to be running fine, and I doubt 40 players runs at 8.9 mspt unless you're doing some extremely wacky stuff to improve performance or they're all in the same area. 
- Which leads to the second point, what were your players doing at the time?
- You're comparing fabric to forge, but we don't have any report from fabric's side to reference from.
- Also optionally, but relevant in the case of servercore - no config files that may be relevant to the performance on the server.
