### ISSUE TITLE
1.20.1 Quilt + Structures lag? -- Not a ServerCore issue

### ISSUE THREAD

**Issue by generrosity** [Wesley1808/ServerCore#66]
**Describe the bug**
When using a datapack with structures, the generation halts for ~ three minutes before giving watchdog issues. When mod is removed, structure generates fine.

The particular datapack we added makes end fortresses more complex, and a new Nether fortress structure. Both of these are fast under heavy modded conditions until ServerCore is added 😓

Sorry - really unsure how to diagnose it further 😔 have loved including ServerCore in all previous servers its strange this has occurred!!

**Reproduce**
 I suggest Prism for quick setup of loaders.
- Latest Quilt
- The Mod
- Datapack: Dungeons and Taverns https://www.planetminecraft.com/data-pack/nova-structures
- Seed -6808035261700636515
- Go to spectator, and to the nether (eg via /execute in minecraft:the_nether run tp generrosity 60 110 294)
   - At this location a Nether  Fortress is generated.

**Expected behavior**
Fast generation of complex structures

**Versions** -Latest is not a version!
ServerCore: 1.3.7+1.30.1
Minecraft: 1.20.1
Quilt Loader: 0.19.2-beta.7

**Mod incompatibilities**
List any installed mods you think might play a role in causing this bug.
- All other mods removed unforutnately.

**Comment by Wesley1808** [comment]
I can't seem to reproduce this with your setup. The structures load without any issues on my end.
To narrow the problem down a bit:
- Was this done on a dedicated server or on a singleplayer world? (I tested on dedicated)
- If you could send over the config, that could help me reproduce it.
- Watchdog crashes have crash reports attached - if you could send those over aswell, that can help give me an idea of what code paths might be causing it.

**Comment by generrosity** [comment]
my appologies - I think I've had a huge brainfart and identified the wrong mod along the way 😅
