### ISSUE TITLE
Blocks not connecting.

### ISSUE THREAD

**Issue by KonekoNyarla** [Wesley1808/ServerCore#68]
**Describe the bug**
When placing down block that update surrounding blocks like double chests, fences, doors, and anything that uses minecraft physics they don't connect.

This is happening on our official DarkRPG modpack servers.

**Reproduce**
Steps to reproduce the behavior: It happens at random on our servers and it can last anywhere from 1-2 hours before going back to normal.

**Expected behavior**
Blocks don't connect/update their state.
https://cdn.discordapp.com/attachments/1077294784877695017/1126606768835940403/image.png
https://media.discordapp.net/attachments/1077294784877695017/1127767695866200074/javaw_NIMXuX83BV.gif

**Versions** -Latest is not a version!
ServerCore: servercore-fabric-1.3.7+1.20.1.jar
Minecraft: 1.20.1

**Mod incompatibilities**
List any installed mods you think might play a role in causing this bug.

**Comment by Wesley1808** [comment]
This is going to be quite difficult to reproduce if it happens at random, under some circumstances I'll probably never encounter myself just testing the pack. I've tried it briefly and didn't have any issues with block connections like this.

Interestingly though ServerCore doesn't really do anything related to this at all.
Are you sure this is what caused the issue, or more like a suspicion that it might be related? Cause it would be pretty unlikely.

**Comment by KonekoNyarla** [comment]
We aren't really sure what mod causes it but we first thought it was lag related but even after removing all players and unloading all chunks the bug was still present and then we reached out to couple of developers and they told us to try and disable all performance mods and we disabled all but ServerCore and it still happened.

The bug is present now on one of our servers if you are interested in testing some things you are welcome to do so.

The modpack name is DarkRPG and it is happening on Witchbane server the ip is: darkrpg.mcserver.ws

I would also like to invite you to out discord server: https://discord.gg/KYaKvQ6K

**Comment by KonekoNyarla** [comment]
The most mindboggling part about this whole thing is that the bug is only present in the overworld if you go to any other dimension blocks work just fine.

**Comment by KonekoNyarla** [comment]
The bug is gone now but if you join our server i'll be able to @you next time it happens

**Comment by Wesley1808** [comment]
I'm not sure if there's anything I can help with in regards to figuring out why this happens, since this very likely isn't anything to do with ServerCore - but I can at least try to do so. My discord is `@wesley1808` by the way, I was already in the linked server.

**Comment by KonekoNyarla** [comment]
I have added the developer role and name of your mod to the profile and any help will be appreciated.
I suppose this can be closed now since you are in the server.
