### ISSUE TITLE
Incompatibility: ServerCore & DynamicFPS causes chunkloading to hang on world generation.

### ISSUE THREAD

**Issue by PlayfulPiano** [Wesley1808/ServerCore#77]
**Describe the bug**
When using ServerCore and DynamicFPS together, building the world generation gets stuck on "generating server chunks" without ever building client chunks. This gets the former's chunk total past twice the goal commonly (~400) and the world never generates. 

**Reproduce**

**Expected behavior**
A clear description of what you expected to happen.

**Versions** -Latest is not a version!
ServerCore: servercore-1.2.9-1.18.2
DynamicFPS: dynamic-fps-3.2.1+minecraft-1.16.5-to-1.18.2
Minecraft: 1.18.2

**Mod incompatibilities**
Dynamic FPS (https://www.curseforge.com/minecraft/mc-mods/dynamic-fps)

Config File Contents:

dynamic_fps.json
[dynamic_fps.txt](https://github.com/Wesley1808/ServerCore/files/12899172/dynamic_fps.txt)

dynamicfps.toml
[dynamicfps.txt](https://github.com/Wesley1808/ServerCore/files/12899170/dynamicfps.txt)

servercore.toml
[servercore.txt](https://github.com/Wesley1808/ServerCore/files/12899164/servercore.txt)

Log:
[latest.log](https://github.com/Wesley1808/ServerCore/files/12899124/latest.log)

Image:
![image](https://github.com/Wesley1808/ServerCore/assets/3158887/8b1cceed-b1f2-4ec8-9402-5a7afe7a2a1b)

**Comment by Wesley1808** [comment]
Can you try to reproduce this with version **[1.3.5+1.18.2?](https://www.curseforge.com/minecraft/mc-mods/servercore/files/4492100)**
1.2.9 is quite old at this point.

**Comment by PlayfulPiano** [comment]
sometimes I wish there were autoupdaters

let me go check quickly

**Comment by PlayfulPiano** [comment]
Nope, issue still happening with v1.3.5 of servercore and v.3.2.1 of dynamicfps.

**Comment by Wesley1808** [comment]
I'll try to see if I can reproduce this. Is this done on a client loading a singleplayer world?

**Comment by PlayfulPiano** [comment]
loading or generating a single player world yes. I'm using quilt instead of fabric in case you can't reproduce it on the latter.

**Comment by Wesley1808** [comment]
This isn't a compat issue between ServerCore and Dynamic FPS, its between Fastload and Dynamic FPS.
ServerCore + Dynamic FPS works fine, and I can reproduce this without servercore.

**Comment by PlayfulPiano** [comment]
Yep, that fixed it! thanks for letting me know what the cause was.

**Comment by PlayfulPiano** [comment]
well then uh
it's now causing a crash in game but it's probably related to a different mod now? idk but i'll post it within fastload's comment.
