### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by Nicolol1234** [Wesley1808/ServerCore#79]
**Describe the bug**
The server crashes at startup

**Reproduce**
- Instal servercore and some mods
- start

**Expected behavior**
The server should start

**Versions** -Latest is not a version!
ServerCore:  fabric-1.3.7
Minecraft: 1.20.1

**Mod incompatibilities**
I have no idea, but here are the logs & crash report:
- logs:
https://mclo.gs/dhV5liW
- crash report:
https://mclo.gs/ZRD9TCu

**Comment by Wesley1808** [comment]
This is very likely to be the conflict between VMP's  `exp_use_optimized_chunk_ticking_iteration` and ServerCore's `optimizations.cache_ticking_chunks`. Both of these try to optimize the same thing in slightly different ways.

Go to `vmp.properties` and set `exp_use_optimized_chunk_ticking_iteration` back to false (its default)
Alternatively you can also set servercore's optimization here to false, that would fix the problem aswell.

**Comment by Nicolol1234** [comment]
Oh ok thanks !
