### ISSUE TITLE
Server crash on start (was working before)

### ISSUE THREAD

**Issue by enzomtpYT** [Wesley1808/ServerCore#82]
**Describe the bug**
A clear description of what the bug is.

**Reproduce**
I don't really know how to reproduce but here is the whole story :

I created a 440 mods modpack, everything was working fine for a whole month.
I tried to add 4 mods : "Tick Statis, Better Fabric Console, Item Blacklist, No Portals"
I saw the server crashing with a simple puzzleslib error, i removed all the new mods and it was still crashing this time with a magnum torch error, ( creator of the mod magnum torch told me it was a servercore problem : https://github.com/Fuzss/magnumtorch/issues/16 )

Everything is server-sided, the server don't really crash it just never pass the error (is stuck when the error happens and nothing more appears in logs)

**Expected behavior**
The server should be starting

**Versions** -Latest is not a version!
ServerCore: 1.3.7
Minecraft: 1.20.1
Quilt: 0.21.1

**Mod incompatibilities**
Yung's API (since there was already a similar problem?)

**Logs**
https://mclo.gs/a8LiSRT

**Error line**
`Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector servercore$updateCachedChunks(Lnet/minecraft/class_3898;)Ljava/lang/Iterable; in #servercore:servercore.common.mixins.json:optimizations.ticking.chunk.cache.ServerChunkCacheMixin from mod servercore failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap servercore-common-refmap.json`

**Comment by Wesley1808** [comment]
Likely duplicate of #79

**Comment by enzomtpYT** [comment]
Yes ! Thanks it was a dupe, sorry for the disbturbance !
