### ISSUE TITLE
startup crash 1.20.1

### ISSUE THREAD

**Issue by kaairu** [Wesley1808/ServerCore#83]
**Describe the bug**
crashes on startup

**Reproduce**
start game

**Expected behavior**
game starts

**Versions** -Latest is not a version!
ServerCore: 1.3.9
Minecraft: 1.20.1

**Mod incompatibilities**
N/A

[latest.log](https://github.com/Wesley1808/ServerCore/files/13212970/latest.log)

**Comment by DonorKrovi** [comment]
+ https://mclo.gs/2gHjEsh

**Comment by Wesley1808** [comment]
Could you try to reproduce this without `combat_next-1.20.1-1.0.1-all.jar`?
I suspect it doesn't like that I updated MixinExtras to the most recent stable release (0.2.0)
