### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by DonorKrovi** [Wesley1808/ServerCore#84]
**Describe the bug**
https://mclo.gs/2gHjEsh

**Reproduce**
start server

**Expected behavior**
A clear description of what you expected to happen.

**Versions** -Latest is not a version!
ServerCore: 1.3.9
Minecraft: 1.20.1

**Mod incompatibilities**
List any installed mods you think might play a role in causing this bug.

**Comment by Wesley1808** [comment]
Are you sure you're not running the 1.20.2 jar? There are some class names in there that would suggest it, but I'm not too familiar with forge logs.
