### ISSUE TITLE
Doesn't apply settings effectively

### ISSUE THREAD

**Issue by Jacosvaldo** [Wesley1808/ServerCore#85]
**Describe the bug**
Bug description:
When values such as max_mobcap and max_view_distance are defined in the config files, they appear as if they were applied when using /servercore status, when in fact they are not, making it necessary to define variables using commands such as /servercore settings mobcaps.

**Reproduce**
- Set values in servercore.toml
- In game use /severcore status
- Compare percentage with loaded monsters
![servercore](https://github.com/Wesley1808/ServerCore/assets/86697348/4d02257b-55eb-4e8f-8999-06a689da29ce)

**Expected behavior**
That the values defined in servercore.toml would apply and not just appear as applied when using /servercore status

**Versions** -Latest is not a version!
ServerCore: servercore-forge-1.3.9+1.20.1
Minecraft: 1.20.1

**Comment by Wesley1808** [comment]
What's the output of `/mobcaps`?
Changes to these do not apply immediately - if there were *already* 70 monsters, you'll have to wait for them to despawn and eventually it will reach the new mobcap target.

**Comment by Jacosvaldo** [comment]
The mod is just BetterF3, but i disable it
Flying to despawn
![1](https://github.com/Wesley1808/ServerCore/assets/86697348/67117cfb-0016-42f1-99c5-04a125fc46c8)

Upon returning to the ground
![2](https://github.com/Wesley1808/ServerCore/assets/86697348/240fef69-7d16-4cd3-bb74-62bbf28d6fc5)

/servercore status
![image](https://github.com/Wesley1808/ServerCore/assets/86697348/1dab56cb-7411-45c9-9f61-5932789950fe)

My servercore.toml (.txt only for uploading):
[servercore.txt](https://github.com/Wesley1808/ServerCore/files/13257377/servercore.txt)

**Comment by Wesley1808** [comment]
Right, that definitely isn't applying correctly.
I can't reproduce this with just ServerCore on the provided version though, this is what it looks like for me:

![2023-11-04_18 12 43](https://github.com/Wesley1808/ServerCore/assets/74668381/aaa2f26d-efa3-4660-af76-eca5d7abd099)

Do you have any other mods that affect the mobcap in any way?

**Comment by Jacosvaldo** [comment]
Not sure maybe ModernFix, Embeddium or Global Gamerules. I'll try without these mods

These are all the mods I'm using:
'Saturn' (version: 0.0.7)
'HT's TreeChop' (version: 0.18.2)
'Not Enough Crashes' (version: 4.4.6+1.20.1)
'Global GameRules' (version: 8.0.0.11)
'Global Packs' (version: 1.16.2_forge)
'Just Enough Items' (version: 15.2.0.27)
'AttributeFix' (version: 21.0.2)
'Rubidium (Embeddium)' (version: 0.7.1)
'Clumps' (version: 12.0.0.3)
'Xaero's World Map' (version: 1.36.0)
'ModernFix' (version: 5.9.0+mc1.20.1)
'Placebo' (version: 8.3.7)
'MixinExtras' (version: 0.2.0-beta.9)
'Bookshelf' (version: 20.1.6)
'Starlight' (version: 1.1.2+forge.1cda73c)
'Catalogue' (version: 1.8.0)
'Balm' (version: 7.1.4)
'Experimental Settings Disabler' (version: 3.0)
'FPS Reducer' (version: 1.20-2.5)
'Cloth Config v12 API' (version: 12.0.109)
'Forge' (version: 47.2.0)
'Embeddium' (version: 0.2.5+mc1.20.1)
'Better Ping Display' (version: 1.1)
'Minecraft' (version: 1.20.1)
'Smoothchunk mod' (version: 1.20.1-3.3)
'OkZoomer' (version: 3.0.1)
'EnchantmentDescriptions' (version: 17.0.8)
'Jade' (version: 11.6.3)
'Chunky' (version: 1.3.92)
'SpectreLib' (version: 0.13.14+1.20.1)
'e4mc' (version: 4.0.1)
'Village Spawn Point' (version: 4.0)
'Kotlin For Forge' (version: 4.5.0)
'TexTrue's Rubidium Options (TexTrue's Embeddium Options)' (version: 1.0.3)
'Xaero's Minimap' (version: 23.8.4)
'Collective' (version: 6.72)
'Fast Workbench' (version: 8.0.2)
'Searchables' (version: 1.0.2)
'Polymorph' (version: 0.49.1+1.20.1)
'FastFurnace' (version: 8.0.1)
'Architectury' (version: 9.1.12)
'AppleSkin' (version: 2.5.1+mc1.20.1)
'Ferrite Core' (version: 6.0.1)
'AI-Improvements' (version: 0.5.2)
'Cupboard utilities' (version: 1.20.1-2.1)
'BetterF3' (version: 7.0.1)
'BetterBurning' (version: 9.0.2)
'TexTrue's Embeddium Options' (version: 0.1.2+mc1.20.1)
'Rebind Narrator' (version: 2.0.2)
'Observable' (version: 4.4.0)
'Let Me Despawn' (version: 1.2.0)
'CosmeticArmorReworked' (version: 1.20.1-v1a)
'Game Menu Mod Option' (version: 2.2.1)
'Default Options' (version: 18.0.1)

**Comment by Jacosvaldo** [comment]
I removed all mods and left only servercore and deleted my servercore.toml, and it continues.
Just touching the servercore.toml it shows the value I configured there (70%).
If I use the command /servercore settings mobcaps 70 it works, but every time I restart modpack I have to use the command again.
![image](https://github.com/Wesley1808/ServerCore/assets/86697348/2fb2f39a-5595-45cb-bca0-f5cc45c4b966)

**Comment by Wesley1808** [comment]
Oh sorry, I misinterpreted the issue. The mobcaps are apparently only modified when the value *changes*, but setting the initial default doesn't count for that. It'll work fine for the dynamic feature (as it automatically changes them based on the mspt), but not in this specific usecase (which tbh it wasn't really designed for), but I'll see if I can fix it for future releases.

**Comment by Jacosvaldo** [comment]
Ok, anyway, thanks for your attention.
