### ISSUE TITLE
Crash Server Forge - ServerHangWatchdog 

### ISSUE THREAD

**Issue by DonorKrovi** [Wesley1808/ServerCore#86]
**Describe the bug**
https://mclo.gs/Oe42jxi

**Reproduce**
Idk

**Expected behavior**
A clear description of what you expected to happen.

**Versions** -Latest is not a version!
ServerCore: servercore-forge-1.3.9+1.20.1
Minecraft: 1.20.1
Config: https://mclo.gs/u6HIAhL

**Mod incompatibilities**
https://mclo.gs/QZ2Ii8l

**Comment by Wesley1808** [comment]
I don't see how servercore has anything to do with this. This can sometimes happen if you have far too many entities, but in this case it looks like it might have to do with an ice dragon? Kinda hard to tell from forge logs but I highly doubt servercore has anything to do with this (nor can I do anything about it).

**Comment by DonorKrovi** [comment]
> I don't see how servercore has anything to do with this. This can sometimes happen if you have far too many entities, but in this case it looks like it might have to do with an ice dragon? Kinda hard to tell from forge logs but I highly doubt servercore has anything to do with this (nor can I do anything about it).

thanks
