### ISSUE TITLE
Villager lobotomization

### ISSUE THREAD

**Issue by Adogs1** [Wesley1808/ServerCore#88]
Villager lobotomization 是否会对利用恐吓村民造出的刷铁傀儡机产生影响？

**Comment by Wesley1808** [comment]
Only if the villagers are both stuck in a 1x1 and are not surrounded by any or standing on a bed at feet height. But most iron farms where villagers are put in 1x1's will have them standing right next to beds as far as I know, so unlikely.

**Comment by Adogs1** [comment]
> 只有当村民们都被困在 1x1 中并且没有被任何人包围或站在英尺高的床上时。但据我所知，大多数村民被安置在 1x1 的铁农场都会让他们站在床边，所以不太可能。

OK，Thanks
