### ISSUE TITLE
Activation range not applied on item entities

### ISSUE THREAD

**Issue by Kirisoup** [Wesley1808/ServerCore#89]
**Describe the bug**
I don't know if this is intended or not, but items seems to not be affected by misc activation range (and other categories). I believe by not ticking items outside the range would dramatically increase performance in some scenarios? Providing a unique category just for items entities would also be lovely (like how zombies are in an unique category separated from monster) 

Edit: Ok this should be a bug. Gonna test and see what is causing it.

**Reproduce**

**Expected behavior**

**Versions**
ServerCore: 1.3.9
Minecraft: 1.20.1 (Quilt loader 0.23.0)

**Mod incompatibilities**

**Comment by Wesley1808** [comment]
They should be affected by it. There are some exclusions though, like when the item entity is moving around it gets temporary immunity to it, preventing tons of item entities getting stuck in item sorters (especially in the nether) as there's no water.

If I might ask, what makes you think they aren't affected by it?

**Comment by Kirisoup** [comment]
> They should be affected by it. There are some exclusions though, like when the item entity is moving around it gets temporary immunity to it, preventing tons of item entities getting stuck in item sorters (especially in the nether) as there's no water.
> 
> If I might ask, what makes you think they aren't affected by it?

Oh ok, so they won't be effected while moving. 

I simply makes a command block teleports an item above itself repeatedly, alongside a similar setup but with a minecart, then moved away, the minecart then stopped in midair while the item is still jumping

**Comment by Kirisoup** [comment]
Are items supposed to somehow still be so performance impactful even if not ticking? If not, I'll try to test again with a clean install

**Comment by Wesley1808** [comment]
I would recommend testing it with [Spark](https://spark.lucko.me/) to see what's causing the lag.

**Comment by Wesley1808** [comment]
I've just tested this myself with 1562 item entities. Inside activation range it took ~43mspt, outside ~6.4ms.

**Comment by Wesley1808** [comment]
Its very possible this was caused by https://github.com/Wesley1808/ServerCore/commit/c106bb26f5c49d8720a7daf16b079f2758594906 as items were sometimes keeping horizontal movement in *many* decimal numbers.

My original test on this was with items spawned in through commands so they probably never had any horizontal movement to begin with.
