### ISSUE TITLE
Game crashed running with this mod

### ISSUE THREAD

**Issue by Artizy2333** [Wesley1808/ServerCore#90]
**Describe the bug**
I added this mod (forge version) with some other mods,when I run mc client,it crashed.But it runs successfully after I remove servercore mod.

**Expected behavior**
I checked my debug file,it tells me another mod doesn't specify minVersion.However,I can
run client without servercore.

**Versions** -Latest is not a version!
ServerCore:ServerCore-Forge-1.3.5+1.18.2
Minecraft:1.18.2

**Comment by Wesley1808** [comment]
Could you provide the crash report for these client crashes with servercore?

I can't do much without the crash report, as I have no way of knowing what could have caused it or what other mods might have conflicted with it.

**Comment by Artizy2333** [comment]
ok,sir this way
https://mclo.gs/rrsYn5L
https://mclo.gs/NNLeUkp

**Comment by Wesley1808** [comment]
Try updating canary, seems like a recent update to it caused it but I believe they fixed it aswell.

**Comment by Artizy2333** [comment]
It works! Thanks a lot
