### ISSUE TITLE
Incompatibility with Chunkloading in 1.3.9/1.20.1

### ISSUE THREAD

**Issue by Sadragos** [Wesley1808/ServerCore#95]
**Describe the bug**
When forceloading a Chunk for example with FTBChunks, Create Loaders or ChunkyMcChunkface the forceloaded Chunks don't get any random Ticks. Machines like furnaces on the other side work as expected. This makes automated Farms near impossible.

**Reproduce**
- In the config enable the dynamic settings, leave everything else as is
- Create a Chunk and forcelead it 
- Plant some wheat-seeds or trees
- Teleport far enough away to not load it with the player
- Set tick speed to a high value (5000) and wait a few seconds
- Return to chunk
- Nothing has grown, but starts as soon, as you get in range again

**Expected behavior**
Apply random ticks to forceloaded Chunks

**Versions** -Latest is not a version!
ServerCore: 1.3.9
Minecraft: 1.20.1

**Mod incompatibilities**
Either of these were tested, none worked
- FTBCHunks
- ChunkyMcChunkface
- Create Loaders

**Comment by Wesley1808** [comment]
I have tried reproducing this with FTB-Chunks on fabric, where random ticks were working fine, even with config options like `cache_ticking_chunks` enabled (which can break some specific random ticking implementations). Just have to make sure forceloading is properly configured in their configuration file or random ticks won't work without servercore either.

For ChunkyMcChunkface I can't say for certain as I haven't tested it yet (testing forge mods in dev environment is painful), but based on quickly scanning the code I'm not even sure if it has any implementation to enable random ticks in their forceloaded chunks. This is still required though, as vanilla forceloaded chunks don't random tick either - in vanilla random ticks are exclusive to chunks nearby non-spectator players.

**Comment by Wesley1808** [comment]
Oh nevermind of course forge has a custom chunk ticking implementation which breaks with the `cache_ticking_chunks` option. You can turn that off in servercore's config to fix it.

**Comment by Sadragos** [comment]
I should have specified,that I'm using forge (47.2.0), sorry. I've also verified, that the random Ticks do indeed occur correctly without ServerCore loaded. I've however not tested changing `cache_ticking_chunks`. Changing it fixed the Problem. Thanks for your help and this nice mod! It really increased my servers performance!

**Comment by Wesley1808** [comment]
With version 1.5.0 and above `cache_ticking_chunks` should now also have better compatibility with most forge/neoforge chunk loader mods. In other cases you can still always just turn it off.
